---

- hosts: all

  environment: "{{ play_environment | d({}) }}"

  vars:

    roles_to_include:
      - user
      - user_packages
      - user_resources
      - crappy_proxy
      - dhcpcd
      - gnupg
      - lightdm
      - localectl
      - sudo
      - virtualbox_guest

  tasks:

    - name: Include custom inventory vars
      include_vars:
        dir: "{{ inventory_file }}.d/vars"
      ignore_errors: yes
      run_once: yes

    - become_user: "{{ system_superuser | d('root') }}"
      block:

        - name: Refresh package list and archlinux-keyring.
          pacman:
            name: archlinux-keyring
            state: latest
            update_cache: yes
          when: ansible_os_family == 'Archlinux'
          become: yes

        - name: Include enabled roles
          include_role:
            name: "{{ current_role }}"
          when: current_role in enabled_roles
          vars:
            role_vars: "{{ enabled_roles[current_role] }}"
          loop_control:
            loop_var: current_role
          with_items: "{{ roles_to_include }}"
